# Generated by Django 5.2.3 on 2025-06-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_student_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="contactno",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
