# Generated by Django 5.2.3 on 2025-06-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_student_description_alter_student_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="description",
        ),
        migrations.AddField(
            model_name="student",
            name="branch",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
