# Generated by Django 5.2.3 on 2025-06-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_remove_student_description_student_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
