# Generated by Django 5.2.3 on 2025-06-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_student_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="description",
        ),
    ]
